In [1]:
import numpy as np

In [2]:
a = np.arange(6)

In [4]:
type(a)

numpy.ndarray

In [5]:
a

array([0, 1, 2, 3, 4, 5])

In [6]:
a[0]

0

In [7]:
a[1]

1

In [8]:
a[:]

array([0, 1, 2, 3, 4, 5])

In [10]:
a2 = a[np.newaxis, :]

In [11]:
a2.shape

(1, 6)

In [12]:
a.shape

(6,)

In [13]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [14]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
a[0,1]

2

In [16]:
a[0]

array([1, 2, 3, 4])

In [17]:
print(a[0])

[1 2 3 4]


In [21]:
a = np.array([1, 2, 3])

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.empty(2)

array([0., 0.])

In [26]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [27]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [28]:
np.arange(2, 8, 2)

array([2, 4, 6])

In [29]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [33]:
b = np.ones(2, dtype=np.int64)

In [35]:
b

array([1, 1], dtype=int64)

In [36]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [37]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [39]:
a = np.sort(arr)

In [40]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
arr = np.sort(arr)

In [60]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
np.argsort(arr)

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [62]:
np.lexsort(arr)

0

In [64]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [65]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [70]:
x

array([[1, 2],
       [3, 4]])

In [71]:
y

array([[5, 6]])

In [72]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [73]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [74]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [75]:
array_example.ndim

3

In [76]:
array_example.size

24

In [77]:
array_example.shape

(3, 2, 4)

In [78]:
a = np.arange(6)

In [79]:
a

array([0, 1, 2, 3, 4, 5])

In [80]:
a.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [81]:
a.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [82]:
a.reshape(6, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [83]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [85]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [86]:
a2 = a[np.newaxis, :]

In [87]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [88]:
a2.shape

(1, 6)

In [89]:
row_vector = a[np.newaxis, :]

In [91]:
row_vector.shape

(1, 6)

In [92]:
a[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [93]:
a[np.newaxis, :]

array([[1, 2, 3, 4, 5, 6]])

In [94]:
data = np.array([1, 2, 3])

In [96]:
data

array([1, 2, 3])

In [97]:
data[0]

1

In [98]:
data[0:2]

array([1, 2])

In [99]:
data[1:]

array([2, 3])

In [100]:
data[-2:]

array([2, 3])

In [106]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [107]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [108]:
a < 5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [109]:
a[a < 5]

array([1, 2, 3, 4])

In [110]:
a >= 5

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [111]:
a[a >= 5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [112]:
a%2==0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [113]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [115]:
(a > 2) & (a < 11)

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False]])

In [116]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
(a > 5) | (a == 5)

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [118]:
a[(a > 5) | (a == 5)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [119]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [121]:
b = np.nonzero(a < 5)

In [122]:
b

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [124]:
list_of_coordinates = list(zip(b[0], b[1]))

In [125]:
list_of_coordinates

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [128]:
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [129]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [131]:
arr1 = a[3:8]

In [132]:
arr1

array([4, 5, 6, 7, 8])

In [133]:
a1 = np.array([[1, 1],
               [2, 2]])

In [134]:
a2 = np.array([[3, 3],
               [4, 4]])

In [135]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [136]:
np.concatenate((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [138]:
np.concatenate((a1, a2), axis=1)

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [139]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [140]:
a = np.arange(1, 15)

In [141]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [142]:
a.reshape(2,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [143]:
np.arange(1, 15).reshape(2, 7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [144]:
x = np.arange(1, 25).reshape(2, 12)

In [145]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [147]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [148]:
np.hsplit(x, 3)[0]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [149]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [183]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [184]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [185]:
a[1,1]

6

In [186]:
a[2,:]

array([ 9, 10, 11, 12])

In [187]:
a[:,2]

array([ 3,  7, 11])

In [188]:
b1 = a[0,:].copy()

In [189]:
b1

array([1, 2, 3, 4])

In [190]:
b1[0] = 99

In [191]:
b1

array([99,  2,  3,  4])

In [192]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [193]:
data = np.array([1, 2])

In [194]:
ones = np.ones(2, dtype=int)

In [195]:
data

array([1, 2])

In [196]:
ones

array([1, 1])

In [197]:
data + ones

array([2, 3])

In [198]:
data - ones

array([0, 1])

In [199]:
data * data

array([1, 4])

In [200]:
data / data

array([1., 1.])

In [201]:
a = np.array([1, 2, 3, 4])

In [202]:
a.sum()

10

In [206]:
b = np.array([[1, 1], [2, 2]])

In [207]:
b

array([[1, 1],
       [2, 2]])

In [204]:
b.sum(axis=0)

array([3, 3])

In [205]:
b.sum(axis=1)

array([2, 4])

In [208]:
data = np.array([1.0, 2.0])

In [209]:
data * 1.6

array([1.6, 3.2])

In [210]:
data.max()

2.0

In [211]:
data.min()

1.0

In [212]:
data.sum()

3.0

In [216]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [217]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [218]:
a.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

In [219]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [220]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [221]:
data[0, 1]

2

In [222]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [223]:
data[0:2, 0]

array([1, 3])

In [225]:
data.max()

6

In [226]:
data.min()

1

In [227]:
data.sum()

21

In [228]:
data = np.array([[1, 2], [5, 3], [4, 6]])

In [229]:
data.max(axis=0)

array([5, 6])

In [230]:
data.max(axis=1)

array([2, 5, 6])

In [231]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])

In [232]:
data + ones

array([[2, 3],
       [4, 5]])

In [233]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])

In [234]:
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [235]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [238]:
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [239]:
np.unique(a, return_index=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14], dtype=int64))

In [240]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [241]:
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

In [242]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [243]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])